all: compile link

compile:
	g++ -IC:/Users/HP/Documents/SFML/src/include -c RecipeGUI.cpp Recipe.cpp

link:
	g++ RecipeGUI.o Recipe.o -o recipe-gui-app -LC:/Users/HP/Documents/SFML/src/lib -lsfml-graphics -lsfml-window -lsfml-system -Wl,-subsystem,console